name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_Er8gNoOg3kUBCXRdSoCgtjs3
          VERCEL_PROJECT_ID: prj_RVTXz4wdPldy8jBOd0NoqJNwUVu0
